/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testLinkedList() {

        LinkedListChallenges sut = new LinkedListChallenges();
        sut.setLinkedListChallenge01();
        assertTrue(true);
    }

    @Test void appendTest(){
        LinkedList<Integer> LL = new LinkedList<>();
        LL.insert(1);
        LL.insert(5);
        LL.insert(9);
        LL.insert(3);

        LL.append(7);

        assertTrue(LL.includes(7));

    }

    @Test void insertBeforeTest(){
        LinkedList<Integer> LL = new LinkedList<>();
        LL.insert(1);
        LL.insert(5);
        LL.insert(9);
        LL.insert(3);

        LL.insertBefore(1, 7);

        String stringTest = LL.toString();
        assertTrue(stringTest.contains("{ 7 } -> { 1 }"));
    }

    @Test void insertAfterTest(){
        LinkedList<Integer> LL = new LinkedList<>();
        LL.insert(1);
        LL.insert(5);
        LL.insert(9);
        LL.insert(3);

        LL.insertAfter(3, 7);
        String stringTest = LL.toString();
        assertTrue((stringTest.contains("{ 3 } -> { 7 }")));
    }

    @Test void kthFromEndTest(){
        LinkedList<Integer> sut = new LinkedList<>();
        sut.insert(1);
        sut.insert(5);
        sut.insert(9);
        sut.insert(3);

        assertEquals(5, sut.kthFromEnd(1));
        assertEquals(9, sut.kthFromEnd(2));
        assertEquals(1, sut.kthFromEnd(0));
        assertEquals(3, sut.kthFromEnd(3));
    }
}
